---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install necessary packages for repository management
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: Add universe repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add multiverse repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Update apt cache after adding repositories
  ansible.builtin.apt:
    update_cache: true
