---
# This is a helper playbook to create necessary vars directories and files
# Run this before running the main playbook to ensure all required files exist

- name: Create necessary vars directories and files
  hosts: localhost
  tasks:
    - name: Create vars directories for all roles
      ansible.builtin.file:
        path: "roles/{{ item }}/vars"
        state: directory
      loop:
        - common
        - ansible_user
        - sudo_config
        - repos
        - oh_my_zsh
        - utilities

    - name: Create default vars files
      ansible.builtin.copy:
        dest: "roles/{{ item }}/vars/default.yml"
        content: "---\n# Default variables for {{ item }} role\n"
        force: no
      loop:
        - common
        - ansible_user
        - sudo_config
        - repos
        - oh_my_zsh
        - utilities

    - name: Create main vars directory
      ansible.builtin.file:
        path: "vars"
        state: directory

    - name: Create default vars file
      ansible.builtin.copy:
        dest: "vars/default.yml"
        content: |
          ---
          # Default variables for all roles
        force: no
