---
- name: Install required packages
  package:
    name:
      - zsh
      - git
      - curl
    state: present

- name: Manage Oh My Zsh installation and configuration for users
  tasks:
    - name: Retrieve user home directory
      command: getent passwd "{{ item }}"
      register: user_home_output
      changed_when: false
      loop: "{{ zsh_config.users }}"
    
    - name: Parse home directory from getent output
      set_fact:
        user_home: "{{ user_home_output.results[item_loop.index0].stdout.split(':')[5] }}"
      loop: "{{ zsh_config.users }}"

    - name: Check if Oh My Zsh is already installed for the user
      stat:
        path: "{{ user_home }}/.oh-my-zsh"
      register: omz
      loop: "{{ zsh_config.users }}"

    - name: Install Oh My Zsh for the user
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        executable: /bin/bash
        creates: "{{ user_home }}/.oh-my-zsh"
      become: yes
      become_user: "{{ item }}"
      when: not omz.results[item_loop.index0].stat.exists
      loop: "{{ zsh_config.users }}"

    - name: Set ZSH as default shell for the user
      user:
        name: "{{ item }}"
        shell: /bin/zsh"