---
- name: Get home directory of {{ user.name }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ user.name }}"
  register: user_info

- name: Set user_home fact
  ansible.builtin.set_fact:
    user_home: "{{ user_info.ansible_facts.getent_passwd[user.name][4] }}"

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: omz_installed

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    executable: /bin/bash
    creates: "{{ user_home }}/.oh-my-zsh"
  become: true
  become_user: "{{ user.name }}"
  when: not omz_installed.stat.exists

- name: Set ZSH as default shell
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /bin/zsh

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    force: yes
  become: true
  become_user: "{{ user.name }}"

- name: Configure .zshrc with Powerlevel10k theme
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    backup: yes
  become: true
  become_user: "{{ user.name }}"

---
# Fixed roles/oh_my_zsh/tasks/main.yml
- name: Install required packages
  ansible.builtin.package:
    name:
      - zsh
      - git
      - curl
    state: present

- name: Configure Oh My Zsh for each user
  ansible.builtin.include_tasks: per_user.yml
  loop: "{{ zsh_config.users }}"
  loop_control:
    loop_var: user
