---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Reload docker
  ansible.builtin.systemd:
    name: docker
    state: reloaded
