---
- name: Create ansible group
  ansible.builtin.group:
    name: ansible
    state: present

- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    group: ansible
    shell: /bin/bash
    create_home: true
    state: present
    comment: "Ansible Automation User"

- name: Ensure ansible user's .ssh directory exists
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'

- name: Set authorized key for ansible user
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ user_config.ansible_user_ssh_key }}"
  when: user_config.ansible_user_ssh_key is defined and user_config.ansible_user_ssh_key | length > 0

- name: Display message if SSH key variable not provided
  ansible.builtin.debug:
    msg: "No SSH key provided in ansible_user_ssh_key variable. You'll need to manually add your SSH key for the ansible user."
  when: user_config.ansible_user_ssh_key is not defined or user_config.ansible_user_ssh_key | length == 0
