---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Install common utility packages
  ansible.builtin.package:
    name: "{{ utilities_common_packages }}"
    state: present

- name: Install OS-specific utility packages
  ansible.builtin.package:
    name: "{{ utilities_os_specific_packages }}"
    state: present
