---
- name: Include OS-specific Docker installation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users is defined and docker_users | length > 0

- name: Configure Docker daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    ansible.builtin.group: root
    mode: '0644'
    backup: true
  notify: restart docker
  when: docker_daemon_config is defined

- name: Ensure Docker daemon configuration directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    ansible.builtin.group: root
    mode: '0755'
