---
- name: Check if sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create sudoers.d directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: '0755'
    owner: root
    ansible.builtin.group: root

- name: Configure passwordless sudo for ansible user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD: ALL"
    owner: root
    ansible.builtin.group: root
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Ensure secure permissions on sudoers file
  ansible.builtin.file:
    path: /etc/sudoers.d/ansible
    owner: root
    ansible.builtin.group: root
    mode: '0440'
