---
utilities_common_packages:
  - htop
  - vim
  - tmux
  - curl
  - wget
  - unzip
  - git
  - jq
  - tree
  - ncdu
  - iotop
  - net-tools
  - dnsutils
  - tcpdump
  - nmap
  - traceroute
  - lsof

utilities_os_specific_packages: []
